delete  from customer;
delete  from employee; 
 

--Inserim dos empleats
INSERT INTO EMPLOYEE (ID, NAME, DATE_OF_BIRTH) VALUES (SEQ_EMPLOYEE.NEXTVAL, 'Treballador 1',TO_DATE('01/01/1980','DD/MM/YYYY'));
INSERT INTO EMPLOYEE (ID, NAME, DATE_OF_BIRTH) VALUES (SEQ_EMPLOYEE.NEXTVAL, 'Treballador 2',TO_DATE('01/07/1990','DD/MM/YYYY'));
INSERT INTO EMPLOYEE (ID, NAME, DATE_OF_BIRTH) VALUES (SEQ_EMPLOYEE.NEXTVAL, 'Treballador 3',TO_DATE('01/10/1970','DD/MM/YYYY'));

--Inserim els clients del primer empleat
INSERT INTO CUSTOMER (ID, NAME, EMPLOYEE_ID) VALUES (SEQ_CUSTOMER.NEXTVAL, 'Client 1.1',24);
INSERT INTO CUSTOMER (ID, NAME, EMPLOYEE_ID) VALUES (SEQ_CUSTOMER.NEXTVAL, 'Client 1.2',24);
INSERT INTO CUSTOMER (ID, NAME, EMPLOYEE_ID) VALUES (SEQ_CUSTOMER.NEXTVAL, 'Client 1.3',24);

--Inserim els clients del segon empleat
INSERT INTO CUSTOMER (ID, NAME, EMPLOYEE_ID) VALUES (SEQ_CUSTOMER.NEXTVAL, 'Client 2.1',25);
INSERT INTO CUSTOMER (ID, NAME, EMPLOYEE_ID) VALUES (SEQ_CUSTOMER.NEXTVAL, 'Client 2.2',25);
INSERT INTO CUSTOMER (ID, NAME, EMPLOYEE_ID) VALUES (SEQ_CUSTOMER.NEXTVAL, 'Client 2.3',25);

--Confirmem
COMMIT;

select * from customer;
select * from EMPLOYEE;