--5. Cread los scripts 
--para añadir el campo SURNAME a EMPLOYEE y CUSTOMER, de tipo VARCHAR2(50 BYTES)

ALTER TABLE EMPLOYEE
ADD (SURNAME VARCHAR2(50));

ALTER TABLE CUSTOMER
ADD (SURNAME VARCHAR2(50));