--Dades b�siques

--Inserim dos empleats
INSERT INTO EMPLOYEE (NAME, SURNAME, DATE_OF_BIRTH) VALUES ('Treballador 1','Cognom treballador 1','01.01.1980');
INSERT INTO EMPLOYEE (NAME, DATE_OF_BIRTH) VALUES ('Treballador 2','01.07.1990');
INSERT INTO EMPLOYEE (NAME, DATE_OF_BIRTH) VALUES ('Treballador 3','01.10.1970');

--Inserim els clients del primer empleat
INSERT INTO CUSTOMER (NAME, EMPLOYEE_ID) VALUES ('Client 1.1',1);
INSERT INTO CUSTOMER (NAME, EMPLOYEE_ID) VALUES ('Client 1.2',1);
INSERT INTO CUSTOMER (NAME, EMPLOYEE_ID) VALUES ('Client 1.3',1);

--Inserim els clients del segon empleat
INSERT INTO CUSTOMER (NAME, EMPLOYEE_ID) VALUES ('Client 2.1',2);
INSERT INTO CUSTOMER (NAME, EMPLOYEE_ID) VALUES ('Client 2.2',2);
INSERT INTO CUSTOMER (NAME, EMPLOYEE_ID) VALUES ('Client 2.3',2);

--Inserim els productes
INSERT INTO PRODUCT (NAME, DESCRIPTION) VALUES ('Product 1', 'Producte bo i car');
INSERT INTO PRODUCT (NAME, DESCRIPTION) VALUES ('Product 2', 'Producte bo i barat');
INSERT INTO PRODUCT (NAME, DESCRIPTION) VALUES ('Product 3', 'Producte bo, bonic i barat');
INSERT INTO PRODUCT (NAME, DESCRIPTION) VALUES ('Product 4', 'Producte de baixa qualita i barat');
INSERT INTO PRODUCT (NAME, DESCRIPTION) VALUES ('Product 5', 'Producte no recomanable');
INSERT INTO PRODUCT (NAME, DESCRIPTION) VALUES ('Product 6', 'Producte amb bona relaci� qualitat preu');
INSERT INTO PRODUCT (NAME, DESCRIPTION) VALUES ('Product 7', 'Producte');
INSERT INTO PRODUCT (NAME) VALUES ('Product 8');
INSERT INTO PRODUCT (NAME) VALUES ('Product 9');
INSERT INTO PRODUCT (NAME) VALUES ('Product 10');
INSERT INTO PRODUCT (NAME) VALUES ('Product 11');
INSERT INTO PRODUCT (NAME) VALUES ('Product 12');
INSERT INTO PRODUCT (NAME) VALUES ('Product 13');

--Relacionem els productes amb els clients
--Client 1.1
INSERT INTO PRODUCT_CUSTOMER(PRODUCT_ID, CUSTOMER_ID, CREATION_DATE) VALUES (1,1,CURRENT TIMESTAMP);
INSERT INTO PRODUCT_CUSTOMER(PRODUCT_ID, CUSTOMER_ID, CREATION_DATE) VALUES (2,1,CURRENT TIMESTAMP);
INSERT INTO PRODUCT_CUSTOMER(PRODUCT_ID, CUSTOMER_ID, CREATION_DATE) VALUES (3,1,CURRENT TIMESTAMP);

--Client 1.2
INSERT INTO PRODUCT_CUSTOMER(PRODUCT_ID, CUSTOMER_ID, CREATION_DATE) VALUES (3,2,CURRENT TIMESTAMP);
INSERT INTO PRODUCT_CUSTOMER(PRODUCT_ID, CUSTOMER_ID, CREATION_DATE) VALUES (4,2,CURRENT TIMESTAMP);
INSERT INTO PRODUCT_CUSTOMER(PRODUCT_ID, CUSTOMER_ID, CREATION_DATE) VALUES (5,2,CURRENT TIMESTAMP);

--Client 1.3
INSERT INTO PRODUCT_CUSTOMER(PRODUCT_ID, CUSTOMER_ID, CREATION_DATE) VALUES (5,3,CURRENT TIMESTAMP);
INSERT INTO PRODUCT_CUSTOMER(PRODUCT_ID, CUSTOMER_ID, CREATION_DATE) VALUES (6,3,CURRENT TIMESTAMP);
INSERT INTO PRODUCT_CUSTOMER(PRODUCT_ID, CUSTOMER_ID, CREATION_DATE) VALUES (7,3,CURRENT TIMESTAMP);

--Client 2.1
INSERT INTO PRODUCT_CUSTOMER(PRODUCT_ID, CUSTOMER_ID, CREATION_DATE) VALUES (7,4,CURRENT TIMESTAMP);
INSERT INTO PRODUCT_CUSTOMER(PRODUCT_ID, CUSTOMER_ID, CREATION_DATE) VALUES (8,4,CURRENT TIMESTAMP);
INSERT INTO PRODUCT_CUSTOMER(PRODUCT_ID, CUSTOMER_ID, CREATION_DATE) VALUES (1,4,CURRENT TIMESTAMP);

--Client 2.2
INSERT INTO PRODUCT_CUSTOMER(PRODUCT_ID, CUSTOMER_ID, CREATION_DATE) VALUES (1,5,CURRENT TIMESTAMP);
INSERT INTO PRODUCT_CUSTOMER(PRODUCT_ID, CUSTOMER_ID, CREATION_DATE) VALUES (3,5,CURRENT TIMESTAMP);
INSERT INTO PRODUCT_CUSTOMER(PRODUCT_ID, CUSTOMER_ID, CREATION_DATE) VALUES (5,5,CURRENT TIMESTAMP);

--Client 2.3
INSERT INTO PRODUCT_CUSTOMER(PRODUCT_ID, CUSTOMER_ID, CREATION_DATE) VALUES (2,6,CURRENT TIMESTAMP);
INSERT INTO PRODUCT_CUSTOMER(PRODUCT_ID, CUSTOMER_ID, CREATION_DATE) VALUES (4,6,CURRENT TIMESTAMP);
